<?php

/**
 * @file
 * Module file for verisure_inline_funnel.
 */

define('VERISURE_INLINE_FUNNEL_LIBRARY_PATH', '/libraries/verisure-inline-funnel');

/**
 * Implements hook_library_info_build().
 *
 * @return array
 */
function verisure_inline_funnel_library_info_build(): array {

  $library = [];

    $paths = verisure_inline_funnel_get_asset_paths();
    if (!array_key_exists('entrypoints', $paths)) {
        \Drupal::logger('verisure_inline_funnel')->warning('Could not parse assets file');
        return $library;
    }

    foreach ($paths['entrypoints'] as $type => $path) {
      if ($type === 'service-worker.js') {
        continue;
      }

      $asset_path = sprintf('%s/%s', VERISURE_INLINE_FUNNEL_LIBRARY_PATH, $path);

      switch (pathinfo($asset_path, PATHINFO_EXTENSION)) {
        case 'js':
          $library['js'][$asset_path] = [];
          break;

        case 'css':
          $library['css']['base'][$asset_path] = [];
          break;
      }
  }

  return $library ? ['funnel-app' => $library] : [];
}

/**
 * @return array
 */
function verisure_inline_funnel_get_asset_paths(): array {
  $manifest_path = sprintf(
    '%s/asset-manifest.json',
    verisure_inline_funnel_path_to_library()
  );

  if ($manifest = json_decode(file_get_contents($manifest_path), TRUE)) {
    return $manifest;
  }

  return [];
}

/**
 * @return string
 */
function verisure_inline_funnel_path_to_library(): string {
  return DRUPAL_ROOT . VERISURE_INLINE_FUNNEL_LIBRARY_PATH;
}
